/*
 * Generated by PEG.js 0.10.0.
 *
 * http://pegjs.org/
 */

"use strict";

function peg$subclass(child, parent) {
  function ctor() { this.constructor = child; }
  ctor.prototype = parent.prototype;
  child.prototype = new ctor();
}

function peg$SyntaxError(message, expected, found, location) {
  this.message  = message;
  this.expected = expected;
  this.found    = found;
  this.location = location;
  this.name     = "SyntaxError";

  if (typeof Error.captureStackTrace === "function") {
    Error.captureStackTrace(this, peg$SyntaxError);
  }
}

peg$subclass(peg$SyntaxError, Error);

peg$SyntaxError.buildMessage = function(expected, found) {
  var DESCRIBE_EXPECTATION_FNS = {
        literal: function(expectation) {
          return "\"" + literalEscape(expectation.text) + "\"";
        },

        "class": function(expectation) {
          var escapedParts = "",
              i;

          for (i = 0; i < expectation.parts.length; i++) {
            escapedParts += expectation.parts[i] instanceof Array
              ? classEscape(expectation.parts[i][0]) + "-" + classEscape(expectation.parts[i][1])
              : classEscape(expectation.parts[i]);
          }

          return "[" + (expectation.inverted ? "^" : "") + escapedParts + "]";
        },

        any: function(expectation) {
          return "any character";
        },

        end: function(expectation) {
          return "end of input";
        },

        other: function(expectation) {
          return expectation.description;
        }
      };

  function hex(ch) {
    return ch.charCodeAt(0).toString(16).toUpperCase();
  }

  function literalEscape(s) {
    return s
      .replace(/\\/g, '\\\\')
      .replace(/"/g,  '\\"')
      .replace(/\0/g, '\\0')
      .replace(/\t/g, '\\t')
      .replace(/\n/g, '\\n')
      .replace(/\r/g, '\\r')
      .replace(/[\x00-\x0F]/g,          function(ch) { return '\\x0' + hex(ch); })
      .replace(/[\x10-\x1F\x7F-\x9F]/g, function(ch) { return '\\x'  + hex(ch); });
  }

  function classEscape(s) {
    return s
      .replace(/\\/g, '\\\\')
      .replace(/\]/g, '\\]')
      .replace(/\^/g, '\\^')
      .replace(/-/g,  '\\-')
      .replace(/\0/g, '\\0')
      .replace(/\t/g, '\\t')
      .replace(/\n/g, '\\n')
      .replace(/\r/g, '\\r')
      .replace(/[\x00-\x0F]/g,          function(ch) { return '\\x0' + hex(ch); })
      .replace(/[\x10-\x1F\x7F-\x9F]/g, function(ch) { return '\\x'  + hex(ch); });
  }

  function describeExpectation(expectation) {
    return DESCRIBE_EXPECTATION_FNS[expectation.type](expectation);
  }

  function describeExpected(expected) {
    var descriptions = new Array(expected.length),
        i, j;

    for (i = 0; i < expected.length; i++) {
      descriptions[i] = describeExpectation(expected[i]);
    }

    descriptions.sort();

    if (descriptions.length > 0) {
      for (i = 1, j = 1; i < descriptions.length; i++) {
        if (descriptions[i - 1] !== descriptions[i]) {
          descriptions[j] = descriptions[i];
          j++;
        }
      }
      descriptions.length = j;
    }

    switch (descriptions.length) {
      case 1:
        return descriptions[0];

      case 2:
        return descriptions[0] + " or " + descriptions[1];

      default:
        return descriptions.slice(0, -1).join(", ")
          + ", or "
          + descriptions[descriptions.length - 1];
    }
  }

  function describeFound(found) {
    return found ? "\"" + literalEscape(found) + "\"" : "end of input";
  }

  return "Expected " + describeExpected(expected) + " but " + describeFound(found) + " found.";
};

function peg$parse(input, options) {
  options = options !== void 0 ? options : {};

  var peg$FAILED = {},

      peg$startRuleIndices = { Start: 0 },
      peg$startRuleIndex   = 0,

      peg$consts = [
        function(head, tail) {
           if(tail.length === 0) return head;
           return createGroup('OR', [head].concat(tail.map(i => i[3])));
         },
        function(head, tail) {
           if(tail.length === 0) return head;
           return createGroup('AND', [head].concat(tail.map(i => i[3])));
         },
        function(left, rh) {
              if (rh === null) return left;
              else if (rh.type === 'arithmetic') {
                return createNode(rh.tail[1], left, rh.tail[3]);
              }
              else return createNode(rh.op, left, rh.right);
            },
        function(e) {
         	return { ...e, parentheses: true }
          },
        peg$otherExpectation("Value"),
        function() {
            return null;
          },
        function() {
              return true;
            },
        function() {
              return false;
            },
        function(ca) {
              return ca[1].join('');
            },
        "TIME",
        peg$literalExpectation("TIME", false),
        "DATE",
        peg$literalExpectation("DATE", false),
        "TIMESTAMP",
        peg$literalExpectation("TIMESTAMP", false),
        function(type, ca) {
              return ca[1].join('');
            },
        function(head, tail) {
            return createList(head, tail);
          },
        peg$otherExpectation("Column"),
        function(l) {
            return { type: 'arithmetic', tail: l };
          },
        function(op, right) {
            return { op, right: right };
          },
        function(op, l) {
            return { op, right: l };
          },
        function(op, begin, end) {
            return { op, right: [begin, end] };
          },
        function(t) { return t[0] + ' ' + t[2]; },
        "<>",
        peg$literalExpectation("<>", false),
        ">=",
        peg$literalExpectation(">=", false),
        "<=",
        peg$literalExpectation("<=", false),
        "<",
        peg$literalExpectation("<", false),
        ">",
        peg$literalExpectation(">", false),
        "!=",
        peg$literalExpectation("!=", false),
        "=",
        peg$literalExpectation("=", false),
        "!",
        peg$literalExpectation("!", false),
        peg$otherExpectation("Optional Whitespace"),
        peg$otherExpectation("Mandatory Whitespace"),
        /^[ \t\n\r]/,
        peg$classExpectation([" ", "\t", "\n", "\r"], false, false),
        "and",
        peg$literalExpectation("AND", true),
        "or",
        peg$literalExpectation("OR", true),
        "not",
        peg$literalExpectation("NOT", true),
        "like",
        peg$literalExpectation("LIKE", true),
        "in",
        peg$literalExpectation("IN", true),
        "between",
        peg$literalExpectation("BETWEEN", true),
        "is",
        peg$literalExpectation("IS", true),
        "null",
        peg$literalExpectation("NULL", true),
        "true",
        peg$literalExpectation("TRUE", true),
        "false",
        peg$literalExpectation("FALSE", true),
        "(",
        peg$literalExpectation("(", false),
        ")",
        peg$literalExpectation(")", false),
        ",",
        peg$literalExpectation(",", false),
        peg$otherExpectation("Number"),
        /^[+\-]/,
        peg$classExpectation(["+", "-"], false, false),
        /^[0-9]/,
        peg$classExpectation([["0", "9"]], false, false),
        /^[.]/,
        peg$classExpectation(["."], false, false),
        function(x) { return parseFloat(recursiveJoin(x)) },
        peg$otherExpectation("String"),
        /^[a-z0-9_%.]/i,
        peg$classExpectation([["a", "z"], ["0", "9"], "_", "%", "."], false, true),
        function(s) { return s.join(""); },
        "-",
        peg$literalExpectation("-", false),
        "+",
        peg$literalExpectation("+", false),
        "\"",
        peg$literalExpectation("\"", false),
        "'",
        peg$literalExpectation("'", false)
      ],

      peg$bytecode = [
        peg$decode(";!"),
        peg$decode("%;\"/\x83#$%;7/>#;;/5$;7/,$;\"/#$+$)($'#(#'#(\"'#&'#0H*%;7/>#;;/5$;7/,$;\"/#$+$)($'#(#'#(\"'#&'#&/)$8\": \"\"! )(\"'#&'#"),
        peg$decode("%;#/\x83#$%;7/>#;:/5$;7/,$;#/#$+$)($'#(#'#(\"'#&'#0H*%;7/>#;:/5$;7/,$;#/#$+$)($'#(#'#(\"'#&'#&/)$8\":!\"\"! )(\"'#&'#"),
        peg$decode("%;$/@#;7/7$;-.\" &\"/)$8#:\"#\"\" )(#'#(\"'#&'#"),
        peg$decode(";,.V &%;D/L#;7/C$;!/:$;7/1$;E/($8%:#%!\")(%'#($'#(#'#(\"'#&'#"),
        peg$decode("<;&=.\" 7$"),
        peg$decode(";'.5 &;(./ &;*.) &;G.# &;)"),
        peg$decode("%;A/& 8!:%! )"),
        peg$decode("%;B/& 8!:&! ).. &%;C/& 8!:'! )"),
        peg$decode("%%;K.\" &\"/A#$;H0#*;H&/1$;K.\" &\"/#$+#)(#'#(\"'#&'#/' 8!:(!! )"),
        peg$decode("%2)\"\"6)7*.5 &2+\"\"6+7,.) &2-\"\"6-7./h#;8/_$%;K.\" &\"/A#$;H0#*;H&/1$;K.\" &\"/#$+#)(#'#(\"'#&'#/)$8#:/#\"\" )(#'#(\"'#&'#"),
        peg$decode("%;&/\x83#$%;7/>#;F/5$;7/,$;%/#$+$)($'#(#'#(\"'#&'#0H*%;7/>#;F/5$;7/,$;%/#$+$)($'#(#'#(\"'#&'#&/)$8\":0\"\"! )(\"'#&'#"),
        peg$decode("<;H=.\" 71"),
        peg$decode(";0./ &;/.) &;1.# &;."),
        peg$decode("%%;7/>#;5/5$;7/,$;%/#$+$)($'#(#'#(\"'#&'#/' 8!:2!! )"),
        peg$decode("%;3/;#;7/2$;%/)$8#:3#\"\" )(#'#(\"'#&'#"),
        peg$decode("%;2/_#;7/V$;D/M$;7/D$;+/;$;7/2$;E/)$8':4'\"&\")(''#(&'#(%'#($'#(#'#(\"'#&'#"),
        peg$decode("%;4/`#;7/W$;G/N$;7/E$;:/<$;7/3$;G/*$8':5'#&$ )(''#(&'#(%'#($'#(#'#(\"'#&'#"),
        peg$decode("%%;</5#;7/,$;>/#$+#)(#'#(\"'#&'#/' 8!:6!! ).# &;>"),
        peg$decode("%%;</5#;7/,$;=/#$+#)(#'#(\"'#&'#/' 8!:6!! ).# &;="),
        peg$decode("%%;</5#;7/,$;?/#$+#)(#'#(\"'#&'#/' 8!:6!! ).# &;?"),
        peg$decode("27\"\"6778.e &29\"\"697:.Y &2;\"\"6;7<.M &2=\"\"6=7>.A &2?\"\"6?7@.5 &2A\"\"6A7B.) &2C\"\"6C7D"),
        peg$decode("2E\"\"6E7F.# &;<"),
        peg$decode("<;8.\" &\"=.\" 7G"),
        peg$decode("<%$;9/&#0#*;9&&&#/\"!&,)=.\" 7H"),
        peg$decode("4I\"\"5!7J"),
        peg$decode("3K\"\"5#7L"),
        peg$decode("3M\"\"5\"7N"),
        peg$decode("3O\"\"5#7P"),
        peg$decode("3Q\"\"5$7R"),
        peg$decode("3S\"\"5\"7T"),
        peg$decode("3U\"\"5'7V"),
        peg$decode("3W\"\"5\"7X"),
        peg$decode("3Y\"\"5$7Z"),
        peg$decode("3[\"\"5$7\\"),
        peg$decode("3]\"\"5%7^"),
        peg$decode("2_\"\"6_7`"),
        peg$decode("2a\"\"6a7b"),
        peg$decode("2c\"\"6c7d"),
        peg$decode("<%%4f\"\"5!7g.\" &\"/\x7F#%$4h\"\"5!7i0)*4h\"\"5!7i&/2#4j\"\"5!7k/#$+\")(\"'#&'#.\" &\"/E$$4h\"\"5!7i/,#0)*4h\"\"5!7i&&&#/#$+#)(#'#(\"'#&'#/' 8!:l!! )=.\" 7e"),
        peg$decode("<%$4n\"\"5!7o/,#0)*4n\"\"5!7o&&&#/' 8!:p!! )=.\" 7m"),
        peg$decode(";H.# &;G"),
        peg$decode("2q\"\"6q7r.) &2s\"\"6s7t"),
        peg$decode("2u\"\"6u7v.) &2w\"\"6w7x")
      ],

      peg$currPos          = 0,
      peg$savedPos         = 0,
      peg$posDetailsCache  = [{ line: 1, column: 1 }],
      peg$maxFailPos       = 0,
      peg$maxFailExpected  = [],
      peg$silentFails      = 0,

      peg$result;

  if ("startRule" in options) {
    if (!(options.startRule in peg$startRuleIndices)) {
      throw new Error("Can't start parsing from rule \"" + options.startRule + "\".");
    }

    peg$startRuleIndex = peg$startRuleIndices[options.startRule];
  }

  function text() {
    return input.substring(peg$savedPos, peg$currPos);
  }

  function location() {
    return peg$computeLocation(peg$savedPos, peg$currPos);
  }

  function expected(description, location) {
    location = location !== void 0 ? location : peg$computeLocation(peg$savedPos, peg$currPos)

    throw peg$buildStructuredError(
      [peg$otherExpectation(description)],
      input.substring(peg$savedPos, peg$currPos),
      location
    );
  }

  function error(message, location) {
    location = location !== void 0 ? location : peg$computeLocation(peg$savedPos, peg$currPos)

    throw peg$buildSimpleError(message, location);
  }

  function peg$literalExpectation(text, ignoreCase) {
    return { type: "literal", text: text, ignoreCase: ignoreCase };
  }

  function peg$classExpectation(parts, inverted, ignoreCase) {
    return { type: "class", parts: parts, inverted: inverted, ignoreCase: ignoreCase };
  }

  function peg$anyExpectation() {
    return { type: "any" };
  }

  function peg$endExpectation() {
    return { type: "end" };
  }

  function peg$otherExpectation(description) {
    return { type: "other", description: description };
  }

  function peg$computePosDetails(pos) {
    var details = peg$posDetailsCache[pos], p;

    if (details) {
      return details;
    } else {
      p = pos - 1;
      while (!peg$posDetailsCache[p]) {
        p--;
      }

      details = peg$posDetailsCache[p];
      details = {
        line:   details.line,
        column: details.column
      };

      while (p < pos) {
        if (input.charCodeAt(p) === 10) {
          details.line++;
          details.column = 1;
        } else {
          details.column++;
        }

        p++;
      }

      peg$posDetailsCache[pos] = details;
      return details;
    }
  }

  function peg$computeLocation(startPos, endPos) {
    var startPosDetails = peg$computePosDetails(startPos),
        endPosDetails   = peg$computePosDetails(endPos);

    return {
      start: {
        offset: startPos,
        line:   startPosDetails.line,
        column: startPosDetails.column
      },
      end: {
        offset: endPos,
        line:   endPosDetails.line,
        column: endPosDetails.column
      }
    };
  }

  function peg$fail(expected) {
    if (peg$currPos < peg$maxFailPos) { return; }

    if (peg$currPos > peg$maxFailPos) {
      peg$maxFailPos = peg$currPos;
      peg$maxFailExpected = [];
    }

    peg$maxFailExpected.push(expected);
  }

  function peg$buildSimpleError(message, location) {
    return new peg$SyntaxError(message, null, null, location);
  }

  function peg$buildStructuredError(expected, found, location) {
    return new peg$SyntaxError(
      peg$SyntaxError.buildMessage(expected, found),
      expected,
      found,
      location
    );
  }

  function peg$decode(s) {
    var bc = new Array(s.length), i;

    for (i = 0; i < s.length; i++) {
      bc[i] = s.charCodeAt(i) - 32;
    }

    return bc;
  }

  function peg$parseRule(index) {
    var bc    = peg$bytecode[index],
        ip    = 0,
        ips   = [],
        end   = bc.length,
        ends  = [],
        stack = [],
        params, i;

    while (true) {
      while (ip < end) {
        switch (bc[ip]) {
          case 0:
            stack.push(peg$consts[bc[ip + 1]]);
            ip += 2;
            break;

          case 1:
            stack.push(void 0);
            ip++;
            break;

          case 2:
            stack.push(null);
            ip++;
            break;

          case 3:
            stack.push(peg$FAILED);
            ip++;
            break;

          case 4:
            stack.push([]);
            ip++;
            break;

          case 5:
            stack.push(peg$currPos);
            ip++;
            break;

          case 6:
            stack.pop();
            ip++;
            break;

          case 7:
            peg$currPos = stack.pop();
            ip++;
            break;

          case 8:
            stack.length -= bc[ip + 1];
            ip += 2;
            break;

          case 9:
            stack.splice(-2, 1);
            ip++;
            break;

          case 10:
            stack[stack.length - 2].push(stack.pop());
            ip++;
            break;

          case 11:
            stack.push(stack.splice(stack.length - bc[ip + 1], bc[ip + 1]));
            ip += 2;
            break;

          case 12:
            stack.push(input.substring(stack.pop(), peg$currPos));
            ip++;
            break;

          case 13:
            ends.push(end);
            ips.push(ip + 3 + bc[ip + 1] + bc[ip + 2]);

            if (stack[stack.length - 1]) {
              end = ip + 3 + bc[ip + 1];
              ip += 3;
            } else {
              end = ip + 3 + bc[ip + 1] + bc[ip + 2];
              ip += 3 + bc[ip + 1];
            }

            break;

          case 14:
            ends.push(end);
            ips.push(ip + 3 + bc[ip + 1] + bc[ip + 2]);

            if (stack[stack.length - 1] === peg$FAILED) {
              end = ip + 3 + bc[ip + 1];
              ip += 3;
            } else {
              end = ip + 3 + bc[ip + 1] + bc[ip + 2];
              ip += 3 + bc[ip + 1];
            }

            break;

          case 15:
            ends.push(end);
            ips.push(ip + 3 + bc[ip + 1] + bc[ip + 2]);

            if (stack[stack.length - 1] !== peg$FAILED) {
              end = ip + 3 + bc[ip + 1];
              ip += 3;
            } else {
              end = ip + 3 + bc[ip + 1] + bc[ip + 2];
              ip += 3 + bc[ip + 1];
            }

            break;

          case 16:
            if (stack[stack.length - 1] !== peg$FAILED) {
              ends.push(end);
              ips.push(ip);

              end = ip + 2 + bc[ip + 1];
              ip += 2;
            } else {
              ip += 2 + bc[ip + 1];
            }

            break;

          case 17:
            ends.push(end);
            ips.push(ip + 3 + bc[ip + 1] + bc[ip + 2]);

            if (input.length > peg$currPos) {
              end = ip + 3 + bc[ip + 1];
              ip += 3;
            } else {
              end = ip + 3 + bc[ip + 1] + bc[ip + 2];
              ip += 3 + bc[ip + 1];
            }

            break;

          case 18:
            ends.push(end);
            ips.push(ip + 4 + bc[ip + 2] + bc[ip + 3]);

            if (input.substr(peg$currPos, peg$consts[bc[ip + 1]].length) === peg$consts[bc[ip + 1]]) {
              end = ip + 4 + bc[ip + 2];
              ip += 4;
            } else {
              end = ip + 4 + bc[ip + 2] + bc[ip + 3];
              ip += 4 + bc[ip + 2];
            }

            break;

          case 19:
            ends.push(end);
            ips.push(ip + 4 + bc[ip + 2] + bc[ip + 3]);

            if (input.substr(peg$currPos, peg$consts[bc[ip + 1]].length).toLowerCase() === peg$consts[bc[ip + 1]]) {
              end = ip + 4 + bc[ip + 2];
              ip += 4;
            } else {
              end = ip + 4 + bc[ip + 2] + bc[ip + 3];
              ip += 4 + bc[ip + 2];
            }

            break;

          case 20:
            ends.push(end);
            ips.push(ip + 4 + bc[ip + 2] + bc[ip + 3]);

            if (peg$consts[bc[ip + 1]].test(input.charAt(peg$currPos))) {
              end = ip + 4 + bc[ip + 2];
              ip += 4;
            } else {
              end = ip + 4 + bc[ip + 2] + bc[ip + 3];
              ip += 4 + bc[ip + 2];
            }

            break;

          case 21:
            stack.push(input.substr(peg$currPos, bc[ip + 1]));
            peg$currPos += bc[ip + 1];
            ip += 2;
            break;

          case 22:
            stack.push(peg$consts[bc[ip + 1]]);
            peg$currPos += peg$consts[bc[ip + 1]].length;
            ip += 2;
            break;

          case 23:
            stack.push(peg$FAILED);
            if (peg$silentFails === 0) {
              peg$fail(peg$consts[bc[ip + 1]]);
            }
            ip += 2;
            break;

          case 24:
            peg$savedPos = stack[stack.length - 1 - bc[ip + 1]];
            ip += 2;
            break;

          case 25:
            peg$savedPos = peg$currPos;
            ip++;
            break;

          case 26:
            params = bc.slice(ip + 4, ip + 4 + bc[ip + 3]);
            for (i = 0; i < bc[ip + 3]; i++) {
              params[i] = stack[stack.length - 1 - params[i]];
            }

            stack.splice(
              stack.length - bc[ip + 2],
              bc[ip + 2],
              peg$consts[bc[ip + 1]].apply(null, params)
            );

            ip += 4 + bc[ip + 3];
            break;

          case 27:
            stack.push(peg$parseRule(bc[ip + 1]));
            ip += 2;
            break;

          case 28:
            peg$silentFails++;
            ip++;
            break;

          case 29:
            peg$silentFails--;
            ip++;
            break;

          default:
            throw new Error("Invalid opcode: " + bc[ip] + ".");
        }
      }

      if (ends.length > 0) {
        end = ends.pop();
        ip = ips.pop();
      } else {
        break;
      }
    }

    return stack[0];
  }



    function createGroup(operator, children) {
    	return {
        type: 'group',
        operator,
        children
      }
    }
    
    function createNode(operator, column, value) {
      return {
        type: 'node',
        operator,
        column,
        value
      }
    }
    
    function createValue(type, value) {
      return {
        type,
        value,
      };
    }
    
    function createList(head, tail) {
      return [head].concat(tail.map(i => i[3]));
    }
    
    function recursiveJoin(a) {
      if(Array.isArray(a)) {
        return a.map(recursiveJoin).join("");
      }

      return a;
    }


  peg$result = peg$parseRule(peg$startRuleIndex);

  if (peg$result !== peg$FAILED && peg$currPos === input.length) {
    return peg$result;
  } else {
    if (peg$result !== peg$FAILED && peg$currPos < input.length) {
      peg$fail(peg$endExpectation());
    }

    throw peg$buildStructuredError(
      peg$maxFailExpected,
      peg$maxFailPos < input.length ? input.charAt(peg$maxFailPos) : null,
      peg$maxFailPos < input.length
        ? peg$computeLocation(peg$maxFailPos, peg$maxFailPos + 1)
        : peg$computeLocation(peg$maxFailPos, peg$maxFailPos)
    );
  }
}

module.exports = {
  SyntaxError: peg$SyntaxError,
  parse:       peg$parse
};
